version: '3'
services:
    dynamodb:
      image: amazon/dynamodb-local:1.21.0
      hostname: dynamodb
      restart: always
      command: -jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/
      volumes:
        - ./.dynamodb-data:/home/dynamodblocal/data
      ports:
        - "8000:8000"
    dynamodb-admin:
      image: aaronshaf/dynamodb-admin:4.5.1
      ports:
        - "8001:8001"
      environment:
        DYNAMO_ENDPOINT: "http://dynamodb:8000"
        AWS_REGION: "ap-southest-2"
        AWS_ACCESS_KEY_ID: local
        AWS_SECRET_ACCESS_KEY: local
      depends_on:
        - dynamodb
volumes:
  dynamodb-data: