service: my-service

plugins:
  - serverless-bundle
  - serverless-dynamodb-local
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x

functions:
  myFunction:
    handler: src/index.handler
    events:
      - sqs:
          arn: "arn:aws:sqs:ap-southeast-2:123456789012:my-queue"